# Generated by Django 5.2.8 on 2025-11-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0003_alter_order_customer_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=30, verbose_name='Téléphone'),
        ),
    ]
